language: csharp
matrix:
  include:
    - os: linux
      dist: focal
      sudo: required
    - os: osx
      osx_image: xcode9.4

branches:
  only:
    - master
    - develop

env:
  global: DOTNET_CLI_TELEMETRY_OPTOUT=1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

dotnet: 5.0.0

script:
  - ./build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
