language: csharp
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      osx_image: xcode9.4

branches:
  only:
    - master
    - develop

env:
  global:
    DOTNET_CLI_TELEMETRY_OPTOUT=1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

mono: latest
dotnet: 2.2.200

script:
  - ./build.sh