image: Visual Studio 2019

branches:
  except:
    - gh-pages

environment:
  SonarKey:
    secure: kexx96aV1FXqk1Xzbi8RrOQpFI037s1Himw4Y0z/LQONHuY6jpei1bYgZvZeI39I
  NuGetKey:
    secure: RcovDx+t7sxpT0DFBRNrYJ5Habd0vLWK5b3YE/oud4KwzREZxgyTYOvoHZR1sm2T
  COVERALLS_REPO_TOKEN:
    secure: W8cqcSrGWp4Uym/aNC6JTVnfuoBQ266qXhkYcAJdc0J5+jbs+trIH5LWvniArf5/
  JAVA_HOME: C:\Program Files\Java\jdk15

build_script:
  - ps: .\build.ps1 appveyor

test: off
deploy: off
